language: python
python:
  - 2.7
  - 3.6
services:
  - docker
before_install:
  - docker-compose up -d --build
install:
  - pip install -r requirements.txt
  - pip install .
script:
  - robot -x xunit.xml tests